layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

 social_media:
  # behance: your_username
  # dribbble: your_username
   facebook: blahblah
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
   linkedin: blahblah
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
   twitter: blahblah
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username
